TARGET         = binder_server
TARGET_TYPE    = executable
LOCAL_SRCS     = src/binder_server.cpp
COMMON_FLAGS   = -Iinclude
EXTRA_CFLAGS   =
EXTRA_CXXFLAGS =
EXTRA_LDFLAGS  = -lbinder \
                 -lutils \
                 -llog
CP_HEADERS     =
CP_RC          =

include $(BUILD_MK)

